version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=kixx
      - MYSQL_USER=kixx
      - MYSQL_PASSWORD=kixxP@ssw0rd
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - kixx-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=kixx
      - PMA_PASSWORD=kixxP@ssw0rd
    ports:
      - '8080:80'
    networks:
      - kixx-network

networks:
  kixx-network:

volumes:
  mysql-data:
